# 실행하려는 서비스(컨테이너)들을 정의합니다.
services:
    # 1. React 프론트엔드 서비스
    graddy-front:
        container_name: graddy-front
        # [수정] build 대신 Docker Hub의 image를 사용하도록 변경
        image: DOCKER_HUB_USERNAME_PLACEHOLDER/graddy-front:latest
        ports:
            - "80:80"
        networks:
            - graddy-net
        restart: always # 항상 재시작 옵션 추가

    # 2. Spring Boot 백엔드 서비스 (Python 스크립트 포함)
    graddy-back:
        container_name: graddy-back
        # [수정] build 대신 Docker Hub의 image를 사용하도록 변경
        image: DOCKER_HUB_USERNAME_PLACEHOLDER/graddy-back:latest
        ports:
            - "8080:8080" # EC2의 8080번 포트를 컨테이너의 8080번 포트와 연결
        # [추가] .env 파일에 있는 환경 변수들을 컨테이너 내부로 주입
        env_file:
            - .env
        networks:
            - graddy-net
        restart: always # 항상 재시작 옵션 추가

# 서비스들이 사용할 네트워크를 정의합니다.
networks:
    graddy-net:
        driver: bridge
