# 실행하려는 서비스(컨테이너)들을 정의합니다.
services:
    # 1. React 프론트엔드 서비스
    graddy-front:
        container_name: graddy-front
        # [수정] build 대신 Docker Hub의 image를 사용하도록 변경
        image: peter4855/graddy-front:latest
        platform: linux/amd64  # ARM64 호환성을 위해 AMD64 플랫폼 지정
        ports:
            - "80:80"
        networks:
            - graddy-net
        restart: always # 항상 재시작 옵션 추가

    # 2. Spring Boot 백엔드 서비스 (Python 스크립트 포함)
    graddy-back:
        container_name: graddy-back
        # [수정] build 대신 Docker Hub의 image를 사용하도록 변경
        image: peter4855/graddy-back:latest
        platform: linux/amd64  # ARM64 호환성을 위해 AMD64 플랫폼 지정
        ports:
            - "8080:8080" # EC2의 8080번 포트를 컨테이너의 8080번 포트와 연결
        # [추가] .env 파일에 있는 환경 변수들을 컨테이너 내부로 주입
        # 배포 스크립트에서 AWS Parameter Store에서 가져온 값으로 .env 파일을 생성함
        env_file:
            - .env
        networks:
            - graddy-net
        restart: always # 항상 재시작 옵션 추가
        depends_on:
            - localstack

    # 3. LocalStack - AWS 서비스 로컬 시뮬레이션
    localstack:
        container_name: localstack
        image: localstack/localstack:latest
        ports:
            - "4566:4566"  # LocalStack 엣지 포트
        environment:
            - SERVICES=s3  # S3 서비스만 활성화
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
            - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./localstack-data:/tmp/localstack"
        networks:
            - graddy-net

# 서비스들이 사용할 네트워크를 정의합니다.
networks:
    graddy-net:
        driver: bridge
