# version: "3.8"

# services:
#     # 백엔드 (Spring Boot)
#     backend:
#         build:
#             context: ./Graddy_back
#             dockerfile: Dockerfile
#         container_name: graddy-backend
#         ports:
#             - "8080:8080"
#         environment:
#             - DB_PASSWORD=${DB_PASSWORD}
#             - SPRING_PROFILES_ACTIVE=prod
#             - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/graddy
#             - SPRING_DATASOURCE_USERNAME=graddy
#         depends_on:
#             - db
#         networks:
#             - graddy-network
#         restart: unless-stopped

#     # 데이터베이스 (MySQL)
#     db:
#         image: mysql:8.0
#         container_name: graddy-mysql
#         environment:
#             - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
#             - MYSQL_DATABASE=graddy
#             - MYSQL_USER=graddy
#             - MYSQL_PASSWORD=${DB_PASSWORD}
#         volumes:
#             - mysql_data:/var/lib/mysql
#         ports:
#             - "3306:3306"
#         networks:
#             - graddy-network
#         restart: unless-stopped

#     # 프론트엔드 (Nginx + React)
#     frontend:
#         image: nginx:alpine
#         container_name: graddy-frontend
#         ports:
#             - "80:80"
#             - "443:443"
#         volumes:
#             - ./Graddy_front/dist:/usr/share/nginx/html
#             - ./nginx.conf:/etc/nginx/conf.d/default.conf
#         depends_on:
#             - backend
#         networks:
#             - graddy-network
#         restart: unless-stopped

# volumes:
#     mysql_data:

# networks:
#     graddy-network:
#         driver: bridge
