# 실행하려는 서비스(컨테이너)들을 정의합니다.
services:
    # 1. React 프론트엔드 서비스
    graddy-front:
        container_name: graddy-front
        # [수정] build 대신 Docker Hub의 image를 사용하도록 변경
        image: peter4855/graddy-front:latest
        ports:
            - "80:80"
        networks:
            - graddy-net
        restart: always # 항상 재시작 옵션 추가

    # 2. Spring Boot 백엔드 서비스 (Python 스크립트 포함)
    graddy-back:
        container_name: graddy-back
        # [수정] build 대신 Docker Hub의 image를 사용하도록 변경
        image: peter4855/graddy-back:latest
        ports:
            - "8080:8080" # EC2의 8080번 포트를 컨테이너의 8080번 포트와 연결
        # [수정] 환경 변수에서 직접 읽어오도록 변경
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - SOLAPI_SENDER_NUMBER=${SOLAPI_SENDER_NUMBER}
            - SOLAPI_API_KEY=${SOLAPI_API_KEY}
            - SOLAPI_API_SECRET=${SOLAPI_API_SECRET}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        networks:
            - graddy-net
        restart: always # 항상 재시작 옵션 추가
        depends_on:
            - localstack

    # 3. FastAPI AI 서비스
    graddy-fastapi:
        container_name: graddy-fastapi
        # [수정] build 대신 Docker Hub의 image를 사용하도록 변경
        image: peter4855/graddy-fastapi:latest
        ports:
            - "8000:8000"  # FastAPI 서버 포트
        # [수정] 환경 변수에서 직접 읽어오도록 변경
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - graddy-net
        restart: always # 항상 재시작 옵션 추가


    # 4. LocalStack - AWS 서비스 로컬 시뮬레이션
    localstack:
        container_name: localstack
        image: localstack/localstack:latest
        ports:
            - "4566:4566"  # LocalStack 엣지 포트
        environment:
            - SERVICES=s3  # S3 서비스만 활성화
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
            - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./localstack-data:/tmp/localstack"
        networks:
            - graddy-net

# 서비스들이 사용할 네트워크를 정의합니다.
networks:
    graddy-net:
        driver: bridge
