# .github/workflows/main.yml

name: Graddy Production CI/CD

on:
    push:
        branches: ["main"]

# Prevent concurrent builds
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# Centralized environment variables
env:
    AWS_REGION: ap-northeast-1
    S3_BUCKET_NAME: mygraddybucket # Your S3 bucket name
    CODE_DEPLOY_APP_NAME: graddy # Your CodeDeploy application name
    CODE_DEPLOY_GROUP_NAME: graddy # Your CodeDeploy deployment group name

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # 1. Check out the repository
            - name: Checkout source code
              uses: actions/checkout@v4

            # 2. Log in to Docker Hub
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            # 2.5. Set up Docker Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # 3. Build and push the Backend Docker image
            - name: Build and push Backend image
              uses: docker/build-push-action@v5
              with:
                  context: ./Graddy_back
                  file: ./Graddy_back/Dockerfile
                  platforms: linux/arm64
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/graddy-back:latest
                  cache-from: type=gha
                  cache-to: type=gha
